### ISSUE TITLE
Generation does not start

### ISSUE THREAD

**Issue by slimanibenbadis** [Rakile/deforumation#6]
Hi, 
I must say beforehand that deforum was working fine before replacing the 2 files.
I did everything in the README file for the installation and the params, and when trying to generate something I got this error inside webui console:

```
Using 0 input frames from E:\Generative-Art\StableDiffusion_A1111\stable-diffusion-webui\outputs/img2img-images\Deforum_20230407175423\inputframes...
Error completing request
Arguments: ('task(98nma71j2j85yx5)', None, False, None, '2D', 120, 'replicate', '0:(0)', '0:(1.0025+0.002*sin(1.25*3.14*t/30))', '0:(0)', '0:(0)', '0:(1.75)', '0:(0.5)', '0:(0.5)', '0:(0)', '0:(0)', '0:(0)', False, '0:(0)', '0:(0)', '0:(0)', '0:(53)', '0: (0.065)', '0: (0.65)', '0: (1.0)', '0: (7)', '0:(1.5)', False, '0:(1)', '0:(0)', False, '0: (25)', '0: (70)', '0: (1)', '0: (200)', '0: (10000)', '0:(s), 1:(-1), "max_f-2":(-1), "max_f-1":(s)', False, '0: ("Euler a")', '0: ("{video_mask}")', False, '0: ("{video_mask}")', False, '0: ("model1.ckpt"), 100: ("model2.safetensors")', False, '0: (2)', True, '0: (1.05)', '0: (5)', '0: (1.0)', '0: (0.1)', '0: (0.0)', 'LAB', '', 1.0, False, '2', 'None', '0: (1)', 'None', '0: (1)', '0', 'perlin', 8, 8, 4, 0.5, True, 0.2, 'border', 'bicubic', False, 'https://deforum.github.io/a1/V1.mp4', 1, 0, -1, False, False, 'https://deforum.github.io/a1/VM1.mp4', False, '20230129210106', '{\n    "0": "tiny cute swamp bunny, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera",\n    "30": "anthropomorphic clean cat, surrounded by fractals, epic angle and pose, symmetrical, 3d, depth of field, ruan jia and fenghua zhong",\n    "60": "a beautiful coconut --neg photo, realistic",\n    "90": "a beautiful durian, trending on Artstation"\n}\n    ', '', '', 512, 512, False, False, -1, 'Euler a', False, 0, 0, 25, 0.0, 1, True, True, False, False, False, 'Deforum_{timestring}', '{timestring}_{index}_{prompt}.png', 'iter', 1, False, False, True, 0.8, 'https://deforum.github.io/a1/I1.png', False, False, False, True, 'https://deforum.github.io/a1/M1.jpg', 1.0, 1.0, 4, 1, True, 4, 'reroll', 10.0, False, 15, False, False, 'FFMPEG mp4', 'None', 'https://deforum.github.io/a1/A1.mp3', False, 'realesr-animevideov3', 'x2', True, False, 'x0_pred', 'C:/SD/20230124234916_%09d.png', 'testvidmanualsettings.mp4', False, 'None', 2, False, 2, False, None, True, False, 'None', True, 'None', False, 'DIS Fine', 'None', False, 'None', False, 'None', False, False, '0:(0.5)', '0:(1)', '0:(0.5)', '0:(1)', '0:(100)', '0:(0)', False, '{\n    "0": "https://deforum.github.io/a1/Gi1.png",\n    "max_f/4-5": "https://deforum.github.io/a1/Gi2.png",\n    "max_f/2-10": "https://deforum.github.io/a1/Gi3.png",\n    "3*max_f/4-15": "https://deforum.github.io/a1/Gi4.jpg",\n    "max_f-20": "https://deforum.github.io/a1/Gi1.png"\n}', '0:(0.75)', '0:(0.35)', '0:(0.25)', '0:(20)', '0:(0.075)', None, None, True, '', '', False, False, False, False, False, 'none', 'None', 1, 0, 1, 64, 64, 64, 'Scale to Fit (Inner Fit)') {}
Traceback (most recent call last):
  File "E:\Generative-Art\StableDiffusion_A1111\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\Generative-Art\StableDiffusion_A1111\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\Generative-Art\StableDiffusion_A1111\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum.py", line 91, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root.animation_prompts, root)
  File "E:\Generative-Art\StableDiffusion_A1111\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\render.py", line 74, in render_animation
    keys = DeformAnimKeys(anim_args, args.seed) if not use_parseq else ParseqAnimKeys(parseq_args, anim_args, video_args)
  File "E:\Generative-Art\StableDiffusion_A1111\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\animation_key_frames.py", line 10, in __init__
    self.angle_series = self.fi.get_inbetweens(self.fi.parse_key_frames(anim_args.angle))
  File "E:\Generative-Art\StableDiffusion_A1111\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\animation_key_frames.py", line 99, in get_inbetweens
    key_frame_series[0] = key_frame_series[key_frame_series.first_valid_index()]
  File "E:\Generative-Art\StableDiffusion_A1111\stable-diffusion-webui\venv\lib\site-packages\pandas\core\series.py", line 981, in __getitem__
    return self._get_value(key)
  File "E:\Generative-Art\StableDiffusion_A1111\stable-diffusion-webui\venv\lib\site-packages\pandas\core\series.py", line 1089, in _get_value
    loc = self.index.get_loc(label)
  File "E:\Generative-Art\StableDiffusion_A1111\stable-diffusion-webui\venv\lib\site-packages\pandas\core\indexes\range.py", line 395, in get_loc
    raise KeyError(key)
KeyError: None
```

Seems like it comes from the render.py file, because when I replaced it by the original, deforum worked again
Also, it does not matter if deforumation has been launched or not, the error is triggered right after I click generate. 

Thanks for looking this up

**Comment by lainollll** [comment]
It works with the latest deforum.  And remember  to check 3D in motion.  You might have some other settings that interfere with render.Py.  Try to help you later if I'm not to drunk tonight.  Might be compatible with your version.  Are you on the latest.

**Comment by lainollll** [comment]
And you started the mediator. Py.   And don't close the mediator cmd window. It must be running in the background

**Comment by slimanibenbadis** [comment]
I am on the latest version of deforum (even deleted the extension and reinstalled it to be sure), everything was running in the background but like I said it does this error with or without mediator and deformuation running in parallel, nothing happens in the console of their respective cmd windows.
Don't worry I am not in a hurry have a good time tonight :)

**Comment by lainollll** [comment]
Write python version

Does it says what version you are on. If not check the windows environments.

**Comment by slimanibenbadis** [comment]
`python --version
Python 3.10.6`

To help a little, it triggers the error right after clicking on generate, the settings are all set by your instructions in the README file.

**Comment by lainollll** [comment]
salmon#7165   my discord
